In [1]:
import numpy as np
a = np.array([[1.0,2.0],[3.0,4.0]])

In [2]:
print(a)

[[1. 2.]
 [3. 4.]]


In [3]:
a.transpose() # 矩阵的转置

array([[1., 3.],
       [2., 4.]])

In [4]:
np.linalg.inv(a) # 矩阵的逆矩阵

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [6]:
u = np.eye(3) # 单位矩阵
print(u)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [8]:
j = np.array([[0.0,-1.0],[1.0,0.0]])
print(j)

[[ 0. -1.]
 [ 1.  0.]]


In [9]:
np.dot(j,j) # 矩阵相乘

array([[-1.,  0.],
       [ 0., -1.]])

In [10]:
np.trace(u) # 矩阵的秩

3.0

In [11]:
y = np.array([[5.],[7.]])
print(y)

[[5.]
 [7.]]


In [12]:
np.linalg.solve(a,y)

array([[-3.],
       [ 4.]])

In [14]:
c,d = np.linalg.eig(j) # 返回矩阵的特征值和特征向量

In [15]:
c

array([0.+1.j, 0.-1.j])

In [16]:
d

array([[0.70710678+0.j        , 0.70710678-0.j        ],
       [0.        -0.70710678j, 0.        +0.70710678j]])