In [1]:
import numpy as np
a = np.floor(10*np.random.random((3,4))) # 这样定义的数组是可以改变的


In [2]:
a

array([[2., 2., 4., 4.],
       [4., 0., 0., 1.],
       [1., 9., 1., 2.]])

In [3]:
a.shape

(3, 4)

In [4]:
# 改变数组的形状
a.ravel() # 将矩阵从左到右，再从上到下，弄成一维数组

array([2., 2., 4., 4., 4., 0., 0., 1., 1., 9., 1., 2.])

In [5]:
a.reshape(2,6) 

array([[2., 2., 4., 4., 4., 0.],
       [0., 1., 1., 9., 1., 2.]])

In [6]:
a.T # 矩阵的转置

array([[2., 4., 1.],
       [2., 0., 9.],
       [4., 0., 1.],
       [4., 1., 2.]])

In [7]:
a.T.shape

(4, 3)

In [8]:
a.shape

(3, 4)

In [9]:
a

array([[2., 2., 4., 4.],
       [4., 0., 0., 1.],
       [1., 9., 1., 2.]])

In [10]:
a.resize((2,6)) # 修改数组本身

In [11]:
a

array([[2., 2., 4., 4., 4., 0.],
       [0., 1., 1., 9., 1., 2.]])

In [12]:
a.reshape(3,-1) # 如果再reshape操作中将维度指定为-1，则会自动计算其他维度

array([[2., 2., 4., 4.],
       [4., 0., 0., 1.],
       [1., 9., 1., 2.]])

In [13]:
a = np.floor(10*np.random.random((2,2)))
a

array([[5., 5.],
       [4., 8.]])

In [14]:
b = np.floor(10*np.random.random((2,2)))
b

array([[0., 8.],
       [1., 5.]])

In [16]:
np.vstack((a,b)) # 将两个数组按垂直方向堆叠在一起

array([[5., 5.],
       [4., 8.],
       [0., 8.],
       [1., 5.]])

In [17]:
np.hstack((a,b)) # 将两个数组按水平方向堆叠在一起

array([[5., 5., 0., 8.],
       [4., 8., 1., 5.]])

In [18]:
from numpy import newaxis
np.column_stack((a,b)) # 将1D数组作为列叠加到2D数组中,它相当于仅用于二维数组的 hstack

array([[5., 5., 0., 8.],
       [4., 8., 1., 5.]])

In [23]:
a = np.array([4.,2.])
b = np.array([3.,8.])

In [20]:
np.column_stack((a,b))

array([[4., 3.],
       [2., 8.]])

In [21]:
np.hstack((a,b))

array([4., 2., 3., 8.])

In [24]:
np.vstack((a,b))

array([[4., 2.],
       [3., 8.]])

In [25]:
a[:,newaxis]

array([[4.],
       [2.]])

In [28]:
b[:,newaxis]

array([[3.],
       [8.]])

In [29]:
np.r_[1:4,0,4]

array([1, 2, 3, 0, 4])

In [30]:
a = np.floor(10*np.random.random((2,12)))

In [31]:
a

array([[9., 1., 7., 3., 4., 3., 1., 1., 0., 2., 9., 3.],
       [3., 8., 5., 3., 5., 8., 9., 5., 3., 0., 2., 6.]])

In [32]:
np.hsplit(a,3)

[array([[9., 1., 7., 3.],
        [3., 8., 5., 3.]]), array([[4., 3., 1., 1.],
        [5., 8., 9., 5.]]), array([[0., 2., 9., 3.],
        [3., 0., 2., 6.]])]

In [34]:
np.hsplit(a,(2,6)) # 使用hsplit，可以沿其水平轴拆分数组，通过指定要返回的均匀划分的数组数量，或者指定要在其后进行划分的列

[array([[9., 1.],
        [3., 8.]]), array([[7., 3., 4., 3.],
        [5., 3., 5., 8.]]), array([[1., 1., 0., 2., 9., 3.],
        [9., 5., 3., 0., 2., 6.]])]

In [36]:
a.array_split(0)

AttributeError: 'numpy.ndarray' object has no attribute 'array_split'

In [46]:
np.array_split(a,3,axis=1) # 按列均匀分成3列

[array([[9., 1., 7., 3.],
        [3., 8., 5., 3.]]), array([[4., 3., 1., 1.],
        [5., 8., 9., 5.]]), array([[0., 2., 9., 3.],
        [3., 0., 2., 6.]])]

In [47]:
np.array_split(a,2,axis=0) # 按行均匀分成两行

[array([[9., 1., 7., 3., 4., 3., 1., 1., 0., 2., 9., 3.]]),
 array([[3., 8., 5., 3., 5., 8., 9., 5., 3., 0., 2., 6.]])]

In [44]:
help(np.array_split)

Help on function array_split in module numpy.lib.shape_base:

array_split(ary, indices_or_sections, axis=0)
    Split an array into multiple sub-arrays.
    
    Please refer to the ``split`` documentation.  The only difference
    between these functions is that ``array_split`` allows
    `indices_or_sections` to be an integer that does *not* equally
    divide the axis. For an array of length l that should be split
    into n sections, it returns l % n sub-arrays of size l//n + 1
    and the rest of size l//n.
    
    See Also
    --------
    split : Split array into multiple sub-arrays of equal size.
    
    Examples
    --------
    >>> x = np.arange(8.0)
    >>> np.array_split(x, 3)
        [array([ 0.,  1.,  2.]), array([ 3.,  4.,  5.]), array([ 6.,  7.])]
    
    >>> x = np.arange(7.0)
    >>> np.array_split(x, 3)
        [array([ 0.,  1.,  2.]), array([ 3.,  4.]), array([ 5.,  6.])]

