In [8]:
import numpy as np
# copy 方法生成数组及其数据的完成拷贝
a = np.arange(12)

In [2]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [11]:
a.shape= 3,4

In [12]:
d = a.copy()

In [13]:
d is a

False

In [14]:
d.base is a

False

In [15]:
d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [16]:
d[0,0]=9999

In [17]:
d

array([[9999,    1,    2,    3],
       [   4,    5,    6,    7],
       [   8,    9,   10,   11]])

In [18]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])