In [2]:
import numpy as np

a = np.arange(12)

In [3]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
b = a # 浅复制 ，但简单赋值不会创建数组对象或其数据的拷贝

In [5]:
b is a

True

In [6]:
b.shape = 3,4


In [7]:
a.shape

(3, 4)

In [8]:
# 使用view方法创建一个新的数组对象，可以使不同的数组对象可以共享相同的数据
c = a.view()

In [9]:
c is a

False

In [10]:
c.base is a

True

In [11]:
c.shape = 2,6

In [12]:
a.shape

(3, 4)

In [13]:
c[0,4]=1234

In [14]:
a

array([[   0,    1,    2,    3],
       [1234,    5,    6,    7],
       [   8,    9,   10,   11]])

In [15]:
s = a[:,1:3]

In [16]:
s

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [17]:
s[:]=10

In [18]:
a

array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])