In [2]:
'''输出Hello World'''
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print("Hello, Pandas")

Hello, Pandas


In [3]:
#对象创建
# 通过传递值列表来创建一个系列，让Pandas创建一个默认的整数索引
import pandas as pd
import numpy as np
s = pd.Series([1,3,5,np.nan,6,8])
print(s)

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64


In [6]:
# 通过传递numpy数组，使用datetime索引和标记列来创建DataFrame
import numpy as np
import pandas as pd
dates = pd.date_range('20180614',periods=7)
print(dates)
print("--"*20)
df = pd.DataFrame(np.random.randn(7,4),index=dates,columns=list("ABCD"))
print(df)

DatetimeIndex(['2018-06-14', '2018-06-15', '2018-06-16', '2018-06-17',
               '2018-06-18', '2018-06-19', '2018-06-20'],
              dtype='datetime64[ns]', freq='D')
----------------------------------------
                   A         B         C         D
2018-06-14  0.745628 -0.077275  1.019681  0.121286
2018-06-15  0.070575  0.476695 -0.578876 -1.438155
2018-06-16 -1.681267  1.749009 -0.453135 -0.468718
2018-06-17  0.847732  1.504192 -0.083250  0.504551
2018-06-18 -1.010202  1.260831  0.506821  1.350066
2018-06-19  0.286510  0.782257 -0.749961  0.419270
2018-06-20 -0.987971  0.890693 -0.813163  0.062710


In [9]:
# 通过传递可以转换为类似系列的对象的字典来创建DataFrame
import numpy as np
import pandas as pd
df = pd.DataFrame({
    'A': 1.,
    'B': pd.Timestamp('20170102'),
    'C': pd.Series(1,index=list(range(4)),dtype='float32'),
    'D' : np.array([3] * 4,dtype='int32'),
    'E' : pd.Categorical(["test","train","test","train"]),
    'F' : 'foo'
})
print(df)
print('---'*20)
print(df.dtypes)

     A          B    C  D      E    F
0  1.0 2017-01-02  1.0  3   test  foo
1  1.0 2017-01-02  1.0  3  train  foo
2  1.0 2017-01-02  1.0  3   test  foo
3  1.0 2017-01-02  1.0  3  train  foo
------------------------------------------------------------
A           float64
B    datetime64[ns]
C           float32
D             int32
E          category
F            object
dtype: object


In [10]:
# 查看数据
# 查看框架的顶部和底部的数据行
import pandas as pd
import numpy as np
dates = pd.date_range('20170101', periods=7)
df = pd.DataFrame(np.random.randn(7,4), index=dates, columns=list('ABCD'))
print(df.head())
print("--------------" * 10)
print(df.tail(3))

                   A         B         C         D
2017-01-01  0.217860 -1.297847  1.153138  0.219613
2017-01-02  0.136234  1.825135 -1.168752 -1.084226
2017-01-03  2.310334 -0.122261  0.106487 -2.176004
2017-01-04 -0.835450  1.189240 -0.414348 -1.797223
2017-01-05  0.556234  1.944720 -0.822767  1.280016
--------------------------------------------------------------------------------------------------------------------------------------------
                   A         B         C         D
2017-01-05  0.556234  1.944720 -0.822767  1.280016
2017-01-06 -0.503083  0.186756  1.368340 -0.570684
2017-01-07 -0.176508  1.666747 -0.242304  2.417399


In [11]:
# 显示索引，列和底层numpy数据
import pandas as pd
import numpy as np

dates = pd.date_range('20170101', periods=7)
df = pd.DataFrame(np.random.randn(7,4), index=dates, columns=list('ABCD'))
print("index is :" )
print(df.index)
print("columns is :" )
print(df.columns)
print("values is :" )
print(df.values)

index is :
DatetimeIndex(['2017-01-01', '2017-01-02', '2017-01-03', '2017-01-04',
               '2017-01-05', '2017-01-06', '2017-01-07'],
              dtype='datetime64[ns]', freq='D')
columns is :
Index(['A', 'B', 'C', 'D'], dtype='object')
values is :
[[-0.69200629 -1.15225189  1.37859526 -1.51062428]
 [-1.651765    0.34910801 -0.15649412  0.32823022]
 [ 0.53424088 -1.20206774  0.34637885 -0.57090573]
 [ 0.92538056  0.34722098  0.30946151  0.98353038]
 [-1.23069885  1.455224   -0.42090375  0.01422661]
 [ 0.07338044  0.38152533  0.1820772   0.36544273]
 [-1.38203709 -0.52475255  0.23427794 -2.33029033]]


In [12]:
# 描述显示数据的快速统计摘要
import pandas as pd
import numpy as np

dates = pd.date_range('20170101', periods=7)
df = pd.DataFrame(np.random.randn(7,4), index=dates, columns=list('ABCD'))
print(df.describe())

              A         B         C         D
count  7.000000  7.000000  7.000000  7.000000
mean   0.695944 -0.051201 -0.171466 -0.478366
std    1.128535  0.619041  1.093343  1.232477
min   -1.202284 -0.695248 -2.265658 -2.235932
25%    0.318811 -0.503395 -0.437830 -1.195096
50%    0.765022 -0.149949 -0.072581 -0.615893
75%    1.117601  0.299617  0.386889  0.205801
max    2.436044  0.894348  1.239860  1.481856


In [13]:
# 调换数据及数组的转置
import pandas as pd
import numpy as np

dates = pd.date_range('20170101', periods=6)
df = pd.DataFrame(np.random.randn(6,4), index=dates, columns=list('ABCD'))
print(df.T)

   2017-01-01  2017-01-02  2017-01-03  2017-01-04  2017-01-05  2017-01-06
A    0.788148    0.873350    0.460439    1.065333    0.705621   -0.658399
B   -1.687456   -2.908424   -0.015910    0.968784    0.211343    0.202217
C   -1.417524    1.385140    0.362841    0.968451   -0.568410   -2.948708
D    0.912517   -1.280129   -0.178245    0.477634    0.899655    0.565513


In [14]:
# 通过轴排序
import pandas as pd
import numpy as np

dates = pd.date_range('20170101', periods=6)
df = pd.DataFrame(np.random.randn(6,4), index=dates, columns=list('ABCD'))
print(df.sort_index(axis=1, ascending=False))

                   D         C         B         A
2017-01-01  0.330775 -1.121714  0.318678 -0.549199
2017-01-02 -1.153364  0.419225  0.401447 -0.552520
2017-01-03 -0.445730  0.399561 -0.044572 -1.615163
2017-01-04  0.063047 -1.154761 -0.476624  0.938343
2017-01-05 -0.277457 -0.245716 -0.805897 -0.473336
2017-01-06 -1.263728  1.773424 -1.421991 -2.679477


In [15]:
# 按值排序
import pandas as pd
import numpy as np

dates = pd.date_range('20170101', periods=6)
df = pd.DataFrame(np.random.randn(6,4), index=dates, columns=list('ABCD'))
print(df.sort_values(by='B'))

                   A         B         C         D
2017-01-03 -0.233780 -1.440747 -0.615195 -1.470323
2017-01-05  0.502524 -0.731272  0.913448  0.185698
2017-01-04  2.108876 -0.193944 -1.491198  0.083391
2017-01-01  0.236044 -0.072867  0.017630  1.453913
2017-01-02  0.629403  0.012406 -1.979554  1.166164
2017-01-06 -0.627634  0.315410 -1.142507 -1.368314


In [17]:
#  选择区块
#  注意虽然用于选择和设置的标准Python/Numpy表达式是直观的，
#  可用于交互式工作，但对于生产代码，但建议使用优化的Pandas
#  数据访问方法.at，.iat，.loc，.iloc和.ix。
#  获取
#  选择一列，产生一个系列，相当于df.A
import pandas as pd
import numpy as np

dates = pd.date_range('20170101', periods=7)
df = pd.DataFrame(np.random.randn(7,4), index=dates, columns=list('ABCD'))

print(df['A'])
print("-------------"*10)
#  选择通过[]操作符，选择切片行.
print(df[0:3])

print("========= 指定选择日期 ========")

print(df['20170102':'20170103'])

2017-01-01    1.365182
2017-01-02    0.846809
2017-01-03    0.090595
2017-01-04   -0.054516
2017-01-05    1.155944
2017-01-06   -0.841337
2017-01-07   -0.153236
Freq: D, Name: A, dtype: float64
----------------------------------------------------------------------------------------------------------------------------------
                   A         B         C         D
2017-01-01  1.365182 -0.866672  0.694184 -0.523985
2017-01-02  0.846809 -0.294397 -1.039713 -0.204326
2017-01-03  0.090595  0.251136 -0.464333  1.954606
========= 指定选择日期 ========
                   A         B         C         D
2017-01-02  0.846809 -0.294397 -1.039713 -0.204326
2017-01-03  0.090595  0.251136 -0.464333  1.954606


In [18]:
# 按标签选择
# 使用标签获取横截面
import pandas as pd
import numpy as np

dates = pd.date_range('20170101', periods=6)
df = pd.DataFrame(np.random.randn(6,4), index=dates, columns=list('ABCD'))

print(df.loc[dates[0]])

A   -0.270257
B    0.418427
C   -0.433454
D    0.171068
Name: 2017-01-01 00:00:00, dtype: float64


In [19]:
#  通过标签选择多轴
import pandas as pd
import numpy as np

dates = pd.date_range('20170101', periods=6)
df = pd.DataFrame(np.random.randn(6,4), index=dates, columns=list('ABCD'))

print(df.loc[:,['A','B']])

                   A         B
2017-01-01  0.378509  1.125766
2017-01-02 -1.151995  1.036891
2017-01-03  0.570254 -0.189260
2017-01-04  0.627972  1.222184
2017-01-05  0.432107  1.411543
2017-01-06 -0.396270 -0.522036


In [20]:
#  显示标签切片，包括两个端点
import pandas as pd
import numpy as np

dates = pd.date_range('20170101', periods=6)
df = pd.DataFrame(np.random.randn(6,4), index=dates, columns=list('ABCD'))

print(df.loc['20170102':'20170104',['A','B']])

                   A         B
2017-01-02  0.690210 -0.820181
2017-01-03  0.806064 -0.872132
2017-01-04 -1.510825 -0.365805


In [21]:
# 减少返回对象的尺寸(大小)
import pandas as pd
import numpy as np

dates = pd.date_range('20170101', periods=6)
df = pd.DataFrame(np.random.randn(6,4), index=dates, columns=list('ABCD'))

print(df.loc['20170102',['A','B']])

A   -0.242236
B    0.769269
Name: 2017-01-02 00:00:00, dtype: float64


In [22]:
# 获得标量值
import pandas as pd
import numpy as np

dates = pd.date_range('20170101', periods=6)
df = pd.DataFrame(np.random.randn(6,4), index=dates, columns=list('ABCD'))

print(df.loc[dates[0],'A'])

-0.13500317024958616


In [23]:
# 快速访问标量(等同于先前的方法)
import pandas as pd
import numpy as np

dates = pd.date_range('20170101', periods=6)
df = pd.DataFrame(np.random.randn(6,4), index=dates, columns=list('ABCD'))

print(df.at[dates[0],'A'])

-1.3833496581196587


In [24]:
# 通过位置选择
# 通过传递的整数的位置选择
import pandas as pd
import numpy as np

dates = pd.date_range('20170101', periods=6)
df = pd.DataFrame(np.random.randn(6,4), index=dates, columns=list('ABCD'))

print(df.iloc[3])

A    0.147941
B   -1.196857
C    1.110731
D    1.250626
Name: 2017-01-04 00:00:00, dtype: float64


In [25]:
# 通过整数切片，类似于numpy/python
import pandas as pd
import numpy as np

dates = pd.date_range('20170101', periods=6)
df = pd.DataFrame(np.random.randn(6,4), index=dates, columns=list('ABCD'))

print(df.iloc[3:5,0:2])

                   A         B
2017-01-04 -1.331305  2.660253
2017-01-05  0.558024  1.719727


In [26]:
# 通过整数位置的列表，类似于numpy/python样式
import pandas as pd
import numpy as np

dates = pd.date_range('20170101', periods=6)
df = pd.DataFrame(np.random.randn(6,4), index=dates, columns=list('ABCD'))

print(df.iloc[[1,2,4],[0,2]])

                   A         C
2017-01-02 -0.335005 -1.585566
2017-01-03  0.050594  0.050930
2017-01-05  1.143703  0.480890


In [27]:
# 明确切片行

In [28]:
# 明确切片行
import pandas as pd
import numpy as np

dates = pd.date_range('20170101', periods=6)
df = pd.DataFrame(np.random.randn(6,4), index=dates, columns=list('ABCD'))

print(df.iloc[1:3,:])

                   A         B         C         D
2017-01-02  1.144502 -0.337938  0.819344 -0.210289
2017-01-03  0.015778 -0.381650  1.008577 -0.289627


In [29]:
# 明确切片列
import pandas as pd
import numpy as np

dates = pd.date_range('20170101', periods=6)
df = pd.DataFrame(np.random.randn(6,4), index=dates, columns=list('ABCD'))

print(df.iloc[:,1:3])

                   B         C
2017-01-01 -1.688748  2.297852
2017-01-02 -1.167515  0.019527
2017-01-03  0.214521 -0.051793
2017-01-04 -1.091072  1.812288
2017-01-05 -1.887389 -0.417972
2017-01-06  0.426093  3.012967


In [32]:
# 要明确获取值
import pandas as pd
import numpy as np

dates = pd.date_range('20170101', periods=6)
df = pd.DataFrame(np.random.randn(6,4), index=dates, columns=list('ABCD'))

print(df.iloc[1,1])

0.2436720755953018


In [31]:
# 要快速访问标量(等同于先前的方法)
import pandas as pd
import numpy as np

dates = pd.date_range('20170101', periods=6)
df = pd.DataFrame(np.random.randn(6,4), index=dates, columns=list('ABCD'))

print(df.iat[1,1])

0.24088466624305752


In [33]:
# 布尔索引
# 使用单列的值来选择数据
import pandas as pd
import numpy as np

dates = pd.date_range('20170101', periods=6)
df = pd.DataFrame(np.random.randn(6,4), index=dates, columns=list('ABCD'))

print(df[df.A > 0])

                   A         B         C         D
2017-01-01  0.537374  0.618934 -0.342191  0.974380
2017-01-02  1.206256 -0.883203 -1.128572  0.149958
2017-01-03  0.611288 -0.113920 -1.794452 -0.476230
2017-01-06  0.845632 -0.217579 -0.739267 -1.991938


In [36]:
# 从满足布尔条件的DataFrame中选择值
import pandas as pd
import numpy as np

dates = pd.date_range('20170101', periods=6)
df = pd.DataFrame(np.random.randn(6,4), index=dates, columns=list('ABCD'))

print(df[df > 0])

                   A   B   C   D
2017-01-01       NaN NaN NaN NaN
2017-01-02  1.029395 NaN NaN NaN
2017-01-03       NaN NaN NaN NaN
2017-01-04  1.266942 NaN NaN NaN
2017-01-05  0.216033 NaN NaN NaN
2017-01-06       NaN NaN NaN NaN


In [37]:
# 使用isin()方法进行过滤
import pandas as pd
import numpy as np

dates = pd.date_range('20170101', periods=6)
df = pd.DataFrame(np.random.randn(6,4), index=dates, columns=list('ABCD'))

df2 = df.copy()
df2['E'] = ['one', 'one','two','three','four','three']

print(df2)

print("============= start to filter =============== ")

print(df2[df2['E'].isin(['two','four'])])

                   A         B         C         D      E
2017-01-01  0.173561 -0.186763  0.042982 -1.070308    one
2017-01-02 -0.305510 -0.280407 -1.146972  1.648637    one
2017-01-03 -0.178233 -0.953657  0.500459 -1.581852    two
2017-01-04  0.129429 -1.332771 -1.130608  2.273053  three
2017-01-05 -1.260241  1.440667  0.793585 -0.655253   four
2017-01-06  1.375862 -0.736900 -0.749187 -0.029387  three
============= start to filter =============== 
                   A         B         C         D     E
2017-01-03 -0.178233 -0.953657  0.500459 -1.581852   two
2017-01-05 -1.260241  1.440667  0.793585 -0.655253  four
